# Generated by Django 3.0.8 on 2020-07-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuctionListing',
            new_name='Listing',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='price',
            new_name='starting_bid',
        ),
    ]
