# Generated by Django 3.0.8 on 2020-07-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200727_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='main_img',
            field=models.ImageField(null=True, upload_to='images_uploaded/<django.db.models.fields.AutoField>/'),
        ),
    ]
