# Generated by Django 3.0.8 on 2020-07-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200730_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='last_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
